# Generated by Django 3.0.6 on 2020-07-02 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0001_initial'),
        ('catalog_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_catalog_item', to='catalog_item.CatalogItem')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_participant', to='participant.Participant')),
            ],
        ),
    ]
