# Generated by Django 3.0.6 on 2020-06-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
