# Generated by Django 3.0.6 on 2020-07-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_item', '0001_initial'),
        ('judge_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgesheet',
            name='catalog_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_item_judge_sheet_set', to='catalog_item.CatalogItem'),
            preserve_default=False,
        ),
    ]
